simulation:

        cars: 2
        duration: 600
        speed:
                index: 
                        - 0
                          #        - 1
                          #        - 2
                value:
                        - 3.638889 # 13.1km/h
                          #        - 8.333333 # 30 km/h
                          #        - 13.88889 # 50 km/h
        model:
                size:
                        - 500
        federated_learning:
                server:
                        epochs: 40
                        m_ratio: 0.5
        strategy: 
                - "random"
                - "m_fastest"
                - "tofl_oracle"
                - "tofl_estimator_dl"
                - "tofl_estimator_m_fastest"
        base_station:
                scenario: "SINGLE_BASE_STATION"
                range: 600
                number: 1
