simulation:
        cars: 100
        mobility:
                distance:
                        x: 1000
                        y: 1000       
                repetitions: 10
        communication:
                repetitions: 30
        speed:
                index: 
                        - 0
                        - 1
                        - 2
                value:
                        - 3.638889 # 13.1km/h
                        - 8.333333 # 30 km/h
                        - 13.88889 # 50 km/h
        model:
                size:
                        - 500
        federated_learning:
                server:
                        epochs: 40
                        m_ratio: 0.5
        strategy: 
                - "random"
                - "m_fastest"
                - "tofl_oracle"
                - "tofl_estimator_dl"
                - "tofl_estimator_m_fastest"
        base_station:
                range: 600
                positions: "communication/base_stations.csv"

