mkdir -p ../data/processed/speed0
mkdir -p ../data/processed/speed1
mkdir -p ../data/processed/speed2
mkdir -p ../data/raw/speed0
mkdir -p ../data/raw/speed1
mkdir -p ../data/raw/speed2
mkdir -p ../mobility/processed/speed0
mkdir -p ../mobility/processed/speed1
mkdir -p ../mobility/processed/speed2
mkdir -p ../mobility/raw/speed0
mkdir -p ../mobility/raw/speed1
mkdir -p ../mobility/raw/speed2
mkdir -p ../results/client_selection/speed0
mkdir -p ../results/client_selection/speed1
mkdir -p ../results/client_selection/speed2
mkdir ../logs
mkdir -p ../results/classification/processed/random
mkdir -p ../results/classification/processed/tofl
mkdir -p ../results/classification/processed/kfastest
